git: Set /repo as safe directory
* https://stackoverflow.com/questions/69470009/git-diff-cached-unknown-option-cached
* Fixes
  git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
    cmdline: git diff --cached --abbrev=40 --full-index --raw
    stderr: 'error: unknown option `cached'
  usage: git diff --no-index [<options>] <path> <path>

Closes #24